Update readme
integritee-network/sgx-setup pull request #4
Opened 2021-11-15 15:36 UTC by haerdib

Not fully tested but should be somewhat in the right direction.

2021-11-18 08:53 UTC, brenzi approved these changes
looks very nice. Looking forward to playing it through at the next occasion

2021-12-04 19:48 UTC, brenzi approved these changes

2021-12-08 08:48 UTC, mosonyi commented
sgxhosts file should contain the hostname and this info is not mentioned in the doc

2021-12-08 14:59 UTC, mosonyi requested changes
Please fix the typo

2021-12-08 14:59 UTC, mosonyi commented on README.md
> +5. Seting up Users:
typo: setting

2021-12-08 15:14 UTC, haerdib commented on README.md
> +5. Seting up Users:
Should be fixed now :)

2021-12-08 15:40 UTC, mosonyi approved these changes
LGTM

2021-12-08 16:10 UTC, merged